import type { SchedulerExpandedPanel, WorkflowStage } from '../../types';
import type { UnconfirmedId } from '../../scheduler/schedulerData';
import type { CtaHintId } from '../../utils/ctaHints';
import type { SchedulerToast } from '../../scheduler/SchedulerRightPane';
import type { MomentId, SchedulerRightSlot } from '@/moments/momentTypes';

export type RightPaneProps = {
  stage: WorkflowStage;
  referralOpen: boolean;
  topSetupVisible: boolean;
  recordingActive: boolean;
  sessionPaused: boolean;
  sessionSeconds: number;
  showHighlight: boolean;
  sleepTableVisible: boolean;
  sleepDisturbanceAccepted: boolean;
  chiefComplaint: string;
  chiefComplaintFocused: boolean;
  mentionVisible: boolean;
  clarificationApplied: boolean;
  leftPanelCollapsed: boolean;
  schedulerExpanded: SchedulerExpandedPanel;
  schedulerReminders: Record<UnconfirmedId, boolean>;
  schedulerSamMoved: boolean;
  schedulerGoodNews: boolean;
  schedulerToasts: SchedulerToast[];
  onSchedulerExpand: (panel: SchedulerExpandedPanel) => void;
  onSchedulerResend: (id: UnconfirmedId) => void;
  onSchedulerMarkSamNoShow: () => void;
  onSchedulerDismissToast: (id: string) => void;
  onOpenSummary: () => void;
  onOpenReferral: () => void;
  onCloseReferral: () => void;
  onBeginSession: (includeUserMessage?: boolean) => void;
  onSleepPosition: () => void;
  onAcceptSleep: () => void;
  onPause: () => void;
  onStop: () => void;
  onChiefComplaintChange: (value: string) => void;
  onChiefComplaintFocus: (focused: boolean) => void;
  onSelectMention: (value: string) => void;
  onDismissClinicalTags: () => void;
  ctaHints: ReadonlySet<CtaHintId>;
  schedulerRightSlot: SchedulerRightSlot;
  clinicalDualRight: boolean;
  momentId: MomentId;
  m3CheckInInvoiceOpen: boolean;
  m3InvoiceInstanceKey: number;
  onM3OpenCheckInFromPanel: () => void;
  onM3CompleteCheckIn: () => void;
};
